############# English navigation ##############

# main menu
[[main]]
weight = 1
name = "Aprende"

[[main]]
name = "Recursos"
pageRef = "pages/elements"
weight = 2

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3

[[main]]
name = "Quienes somos"
weight = 4

[[main]]
parent = "Aprende"
name = "Básico"
pageRef = "pages/abc-de-bitcoin"
weight = 1

[[main]]
parent = "Aprende"
name = "Intermedio"
pageRef = "pages/intermedio"
weight = 2

[[main]]
parent = "Aprende"
name = "Cursos y asesorías"
pageRef = "pages/elements"
weight = 3

[[main]]
parent = "Quienes somos"
name = "Acerca de PB"
pageRef = "/about"

[[main]]
parent = "Quienes somos"
name = "Autores"
pageRef = "/authors"

#[[main]]
#parent = "Aprende"
#name = "Blog"
#pageRef = "/blog"

#[[main]]
#parent = "Aprende"
#name = "Contact"
#pageRef = "/contact"

#[[main]]
#parent = "Aprende"
#name = "Categories"
#pageRef = "/categories"

#[[main]]
#parent = "Aprende"
#name = "404 Page"
#pageRef = "/404"

# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
