############# English navigation ##############

# main menu
[[main]]
name = "Blog"
pageRef = "/blog"
weight = 3

[[main]]
name = "Quienes somos"
pageRef = "/about"
weight = 4

[[main]]
name = "Recursos"
pageRef = "pages/elements"
weight = 2

[[main]]
weight = 1
name = "Aprende"

#[[main]]
#parent = "Aprende"
#name = "Blog"
#pageRef = "/blog"

[[main]]
parent = "Aprende"
name = "Contact"
pageRef = "/contact"

[[main]]
parent = "Aprende"
name = "Authors"
pageRef = "/authors"

[[main]]
parent = "Aprende"
name = "Categories"
pageRef = "/categories"

[[main]]
parent = "Aprende"
name = "404 Page"
pageRef = "/404"


# footer menu
[[footer]]
name = "About"
pageRef = "/about"
weight = 1

[[footer]]
name = "Elements"
pageRef = "/elements"
weight = 2

[[footer]]
name = "Privacy Policy"
pageRef = "/privacy-policy"
weight = 3
